services:
  db:
    image: postgres:latest
    ports: ["5432:5432"]
    restart: always
    environment:
      POSTGRES_USER: questymuse
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_DB: tasks